<div align="right" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/Logo blue_dark.png"  style="width:25px" align="right";/>
</div>

# Subquery in FROM 
© ExploreAI Academy

> ⚠️ This notebook will not run on Google Colab because it cannot connect to a local database. Please make sure that this notebook is running on the same local machine as your MySQL Workbench installation and MySQL `united_nations` database.

## Description

In this lesson we will use a subquery like a temporary table, meaning we will do a calculation, and then reference the result of that calculation in another query.

## Learning objectives

In this train we will learn:
- How to create a query using the FROM clause.

## Connecting to our MySQL database

Using our `Access_to_Basic_Services` table in our `united_nations` database we created in MySQL Workbench, we want to answer some questions about our dataset. We can apply the same queries we used in MySQL Workbench in this notebook if we connect to our MySQL server by running the cells below.

Note that before, for this tutorial, we will already have worked through the lessons where the `united_nations.Basic_Services` table, `united_nations.Economic_Indicators` table, and the `united_nations.Geographic_Locations` table have been created.

In [1]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook. 
# If you get an error here, make sure that mysql and pymysql are installed correctly. 

%load_ext sql

In [2]:
# Establish a connection to the local database using the '%sql' magic command.
# Replace 'password' with our connection password and `db_name` with our database name. 
# If you get an error here, please make sure the database name or password is correct.

%sql mysql+pymysql://root:Dau/2022@localhost:3306/united_nations

'Connected: root@united_nations'


To make a query, we add the `%%sql` command to the start of a cell, create one open line then the query like below, and run the cell.

In [3]:
%%sql

SELECT 
    *
FROM
    Access_to_Basic_Services
LIMIT 5;

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, Decimal('94.67'), Decimal('98.00'), Decimal('17.542806'), Decimal('184.39'), Decimal('2699700.00'), Decimal('4.93')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, Decimal('94.67'), Decimal('98.00'), Decimal('17.794055'), Decimal('137.28'), Decimal('2699700.00'), Decimal('4.96')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, Decimal('95.00'), Decimal('98.00'), Decimal('18.037776'), Decimal('166.81'), Decimal('2699700.00'), Decimal('4.90')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, Decimal('95.00'), Decimal('98.00'), Decimal('18.276452'), Decimal('179.34'), Decimal('2699700.00'), Decimal('4.85')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, Decimal('95.00'), Decimal('98.00'), Decimal('18.513673'), Decimal('181.67'), Decimal('2699700.00'), Decimal('4.80'))]

## Exercise

In this exercise. We will use a subquery to answer the following question: What is the average GDP and population for countries with unemployment rates above 5%?

### Creating the subquery
Construct the subquery that displays the average GDP and average population of countries for 2020. The query should have the following columns: `Country_name`, `Avg_GDP`, `Avg_Population`.

In [5]:
%%sql

SELECT 
    Country_name,
    AVG(Est_gdp_in_billions) AS Avg_GDP,
    AVG(Est_population_in_millions) AS Avg_Population
FROM
    Economic_Indicators
GROUP BY
    Country_name;

 * mysql+pymysql://root:***@localhost:3306/united_nations
182 rows affected.

[('Afghanistan', Decimal('19.063333'), Decimal('36.2436061667')),
 ('Algeria', Decimal('164.633333'), Decimal('41.5171783333')),
 ('American Samoa', Decimal('0.660000'), Decimal('0.0488688333')),
 ('Angola', Decimal('67.791667'), Decimal('30.7577836667')),
 ('Anguilla', None, None),
 ('Antigua and Barbuda', Decimal('1.416667'), Decimal('0.0905413333')),
 ('Argentina', Decimal('525.670000'), Decimal('44.2628536667')),
 ('Armenia', Decimal('11.891667'), Decimal('2.8431866667')),
 ('Aruba', Decimal('2.970000'), Decimal('0.1045655000')),
 ('Australia', Decimal('1338.516667'), Decimal('24.7605421667')),
 ('Azerbaijan', Decimal('44.963333'), Decimal('9.8863935000')),
 ('Bahamas', None, None),
 ('Bahrain', Decimal('34.986667'), Decimal('1.4479390000')),
 ('Bangladesh', Decimal('300.098333'), Decimal('162.6716105000')),
 ('Barbados', Decimal('4.936667'), Decimal('0.2794133333')),
 ('Belize', Decimal('2.261667'), Decimal('0.3779931667')),
 ('Benin', Decimal('13.368333'), Decimal('11.7773161667')),
 ('Bermuda', Decimal('7.038333'), Decimal('0.0642310000')),
 ('Bhutan', Decimal('2.321667'), Decimal('0.7585361667')),
 ('Bolivia (Plurinational State of)', None, None),
 ('Botswana', Decimal('15.563333'), Decimal('2.4261566667')),
 ('Brazil', Decimal('1816.700000'), Decimal('209.2830861667')),
 ('British Virgin Islands', None, Decimal('0.0301700000')),
 ('Brunei Darussalam', Decimal('12.585000'), Decimal('0.4319590000')),
 ('Burkina Faso', Decimal('14.795000'), Decimal('20.1160605000')),
 ('Burundi', Decimal('2.723333'), Decimal('11.3957675000')),
 ('Cabo Verde', Decimal('1.780000'), Decimal('0.5677310000')),
 ('Cambodia', Decimal('22.963333'), Decimal('15.9171066667')),
 ('Cameroon', Decimal('37.088333'), Decimal('24.7446053333')),
 ('Canada', Decimal('1641.090000'), Decimal('36.8435248333')),
 ('Cayman Islands', Decimal('4.810000'), Decimal('0.0615830000')),
 ('Central African Republic', Decimal('2.061667'), Decimal('5.0612291667')),
 ('Chad', Decimal('10.720000'), Decimal('15.3657533333')),
 ('Chile', Decimal('265.811667'), Decimal('18.5606383333')),
 ('China', Decimal('12911.278333'), Decimal('1397.5783333333')),
 ('Colombia', Decimal('302.633333'), Decimal('48.9153971667')),
 ('Comoros', Decimal('1.090000'), Decimal('0.7610822000')),
 ('Congo', None, None),
 ('Cook Islands', None, None),
 ('Costa Rica', Decimal('60.801667'), Decimal('5.0137766667')),
 ("Côte d'Ivoire", None, None),
 ('Cuba', Decimal('97.696667'), Decimal('11.3273250000')),
 ('Curaçao', None, None),
 ('Cyprus', Decimal('23.410000'), Decimal('1.2131480000')),
 ("Democratic People's Republic of Korea", None, None),
 ('Democratic Republic of the Congo', None, None),
 ('Djibouti', Decimal('2.826667'), Decimal('1.0485168333')),
 ('Dominica', Decimal('0.546667'), Decimal('0.0701616667')),
 ('Dominican Republic', Decimal('80.033333'), Decimal('10.7046241667')),
 ('Ecuador', Decimal('103.081667'), Decimal('16.8800730000')),
 ('Egypt', None, None),
 ('El Salvador', Decimal('25.011667'), Decimal('6.2662533333')),
 ('Equatorial Guinea', Decimal('12.210000'), Decimal('1.3988646667')),
 ('Eritrea', None, Decimal('3.3526465000')),
 ('Eswatini', Decimal('4.238333'), Decimal('1.1564243333')),
 ('Ethiopia', Decimal('84.750000'), Decimal('109.7340026667')),
 ('Falkland Islands (Malvinas)', None, None),
 ('Fiji', Decimal('5.083333'), Decimal('0.9187455000')),
 ('French Guiana', None, None),
 ('French Polynesia', Decimal('5.751667'), Decimal('0.2966701667')),
 ('Gabon', Decimal('15.396667'), Decimal('2.1637180000')),
 ('Gambia', None, None),
 ('Georgia', Decimal('16.206667'), Decimal('3.7250351667')),
 ('Ghana', Decimal('61.945000'), Decimal('30.5368060000')),
 ('Greenland', Decimal('2.865000'), Decimal('0.0561810000')),
 ('Grenada', Decimal('1.063333'), Decimal('0.1199556667')),
 ('Guadeloupe', None, None),
 ('Guam', Decimal('6.005000'), Decimal('0.1685771667')),
 ('Guatemala', Decimal('71.336667'), Decimal('16.2153060000')),
 ('Guinea', Decimal('11.198333'), Decimal('12.4058880000')),
 ('Guinea-Bissau', Decimal('1.325000'), Decimal('1.9024228333')),
 ('Guyana', Decimal('4.823333'), Decimal('0.7764731667')),
 ('Haiti', Decimal('14.936667'), Decimal('10.9368015000')),
 ('Honduras', Decimal('23.138333'), Decimal('9.7092645000')),
 ('India', Decimal('2542.005000'), Decimal('1360.7001680000')),
 ('Indonesia', Decimal('1004.735000'), Decimal('265.6581158333')),
 ('Iran (Islamic Republic of)', None, None),
 ('Iraq', Decimal('194.328333'), Decimal('40.1313536667')),
 ('Israel', Decimal('362.698333'), Decimal('8.7985500000')),
 ('Jamaica', Decimal('14.741667'), Decimal('2.8085933333')),
 ('Japan', Decimal('4930.120000'), Decimal('126.8156666667')),
 ('Jordan', Decimal('42.105000'), Decimal('10.2935920000')),
 ('Kazakhstan', Decimal('170.095000'), Decimal('18.1534046667')),
 ('Kenya', Decimal('86.705000'), Decimal('49.4308048333')),
 ('Kiribati', Decimal('0.183333'), Decimal('0.1214245000')),
 ('Kuwait', Decimal('120.840000'), Decimal('4.2000768333')),
 ('Kyrgyzstan', None, None),
 ("Lao People's Democratic Republic", None, None),
 ('Lebanon', Decimal('48.778333'), Decimal('6.0270800000')),
 ('Lesotho', Decimal('2.335000'), Decimal('2.1851381667')),
 ('Liberia', Decimal('3.300000'), Decimal('4.8462201667')),
 ('Libya', Decimal('60.346667'), Decimal('6.4255858333')),
 ('Madagascar', Decimal('12.876667'), Decimal('26.5212078333')),
 ('Malawi', Decimal('8.971667'), Decimal('18.1396690000')),
 ('Malaysia', Decimal('330.505000'), Decimal('32.1623901667')),
 ('Maldives', Decimal('4.650000'), Decimal('0.4784966667')),
 ('Mali', Decimal('15.720000'), Decimal('19.6416883333')),
 ('Marshall Islands', Decimal('0.213333'), Decimal('0.0465093333')),
 ('Martinique', None, None),
 ('Mauritania', Decimal('7.220000'), Decimal('4.2185483333')),
 ('Mauritius', Decimal('13.148333'), Decimal('1.2645741667')),
 ('Mayotte', None, None),
 ('Mexico', Decimal('1165.201667'), Decimal('123.2676416667')),
 ('Micronesia (Federated States of)', None, None),
 ('Mongolia', Decimal('12.496667'), Decimal('3.1301816667')),
 ('Montserrat', None, None),
 ('Morocco', Decimal('119.688333'), Decimal('35.7060880000')),
 ('Mozambique', Decimal('14.230000'), Decimal('28.9994820000')),
 ('Myanmar', Decimal('66.593333'), Decimal('52.4656771667')),
 ('Namibia', Decimal('11.960000'), Decimal('2.3853353333')),
 ('Nauru', Decimal('0.108333'), Decimal('0.0117791667')),
 ('Nepal', Decimal('29.763333'), Decimal('28.3904620000')),
 ('New Caledonia', Decimal('9.226667'), Decimal('0.2706700000')),
 ('New Zealand', Decimal('201.771667'), Decimal('4.8511833333')),
 ('Nicaragua', Decimal('13.010000'), Decimal('6.5267361667')),
 ('Niger', Decimal('11.790000'), Decimal('22.1903131667')),
 ('Nigeria', Decimal('429.248333'), Decimal('196.0296905000')),
 ('Niue', None, None),
 ('Northern Mariana Islands', Decimal('1.236000'), Decimal('0.0505208333')),
 ('Oman', Decimal('81.696667'), Decimal('4.4798373333')),
 ('Pakistan', Decimal('316.811667'), Decimal('218.5158821667')),
 ('Palau', Decimal('0.280000'), Decimal('0.0178665000')),
 ('Panama', Decimal('60.015000'), Decimal('4.1286135000')),
 ('Papua New Guinea', Decimal('22.988333'), Decimal('9.2195820000')),
 ('Paraguay', Decimal('37.481667'), Decimal('6.3986696667')),
 ('Peru', Decimal('207.558333'), Decimal('31.9639481667')),
 ('Philippines', Decimal('339.828333'), Decimal('107.6309581667')),
 ('Puerto Rico', Decimal('103.380000'), Decimal('3.3122960000')),
 ('Qatar', Decimal('163.025000'), Decimal('2.6759743333')),
 ('Republic of Korea', None, None),
 ('Réunion', None, None),
 ('Rwanda', Decimal('9.443333'), Decimal('12.3862325000')),
 ('Saint Barthélemy', None, None),
 ('Saint Helena', None, None),
 ('Saint Kitts and Nevis', None, None),
 ('Saint Lucia', None, None),
 ('Saint Martin (French Part)', None, None),
 ('Saint Pierre and Miquelon', None, None),
 ('Saint Vincent and the Grenadines', None, None),
 ('Samoa', Decimal('0.866667'), Decimal('0.2088800000')),
 ('Sao Tome and Principe', Decimal('0.393333'), Decimal('0.2097293333')),
 ('Saudi Arabia', Decimal('718.561667'), Decimal('34.5336403333')),
 ('Senegal', Decimal('21.470000'), Decimal('15.3795233333')),
 ('Seychelles', Decimal('1.560000'), Decimal('0.0956652000')),
 ('Sierra Leone', Decimal('3.973333'), Decimal('7.7713883333')),
 ('Singapore', Decimal('344.631667'), Decimal('5.6304316667')),
 ('Sint Maarten (Dutch part)', Decimal('1.233333'), Decimal('0.0397893333')),
 ('Solomon Islands', Decimal('1.490000'), Decimal('0.6516381667')),
 ('Somalia', Decimal('5.950000'), Decimal('15.1417306667')),
 ('South Africa', Decimal('363.676667'), Decimal('57.1947673333')),
 ('South Sudan', Decimal('12.000000'), Decimal('10.7279753333')),
 ('Sri Lanka', Decimal('89.396667'), Decimal('21.5015000000')),
 ('State of Palestine', None, None),
 ('Sudan', Decimal('68.225000'), Decimal('41.3166355000')),
 ('Suriname', Decimal('3.828333'), Decimal('0.5909280000')),
 ('Syrian Arab Republic', Decimal('16.718333'), Decimal('19.5595186667')),
 ('Tajikistan', Decimal('7.833333'), Decimal('9.0305413333')),
 ('Thailand', Decimal('470.256667'), Decimal('70.9518108333')),
 ('Timor-Leste', Decimal('1.765000'), Decimal('1.2526480000')),
 ('Togo', Decimal('6.418333'), Decimal('7.9532885000')),
 ('Tokelau', None, None),
 ('Tonga', Decimal('0.466667'), Decimal('0.1054331667')),
 ('Trinidad and Tobago', Decimal('23.896667'), Decimal('1.4918208333')),
 ('Tunisia', Decimal('43.240000'), Decimal('11.8664945000')),
 ('Türkiye', None, None),
 ('Turkmenistan', Decimal('39.180000'), Decimal('6.0128831667')),
 ('Turks and Caicos Islands', Decimal('1.025000'), Decimal('0.0390287500')),
 ('Tuvalu', Decimal('0.048333'), Decimal('0.0109078333')),
 ('Uganda', Decimal('33.035000'), Decimal('40.8703043333')),
 ('United Arab Emirates', Decimal('387.428333'), Decimal('9.1030955000')),
 ('United Republic of Tanzania', None, None),
 ('United States of America', None, None),
 ('United States Virgin Islands', None, None),
 ('Uruguay', Decimal('59.008333'), Decimal('3.4205535000')),
 ('Uzbekistan', Decimal('67.808333'), Decimal('32.7173166667')),
 ('Vanuatu', Decimal('0.856667'), Decimal('0.2938803333')),
 ('Venezuela (Bolivarian Republic of)', None, None),
 ('Viet Nam', None, None),
 ('Wallis and Futuna Islands', None, None),
 ('Yemen', None, None),
 ('Zambia', Decimal('22.635000'), Decimal('17.5763550000')),
 ('Zimbabwe', Decimal('22.598333'), Decimal('14.9058666667'))]

### Creating the main query
Construct a query that filters out countries with unemployment rates above 5%. The query should include the following columns: `Country_name`, `Est_gdp_in_billions`,  `Est_population_in_millions`.

In [6]:
%%sql

SELECT 
    Country_name,
    Est_gdp_in_billions,
    Est_population_in_millions
FROM
    Economic_Indicators
WHERE
    Pct_unemployment > 5
    AND Time_period = 2020;

 * mysql+pymysql://root:***@localhost:3306/united_nations
37 rows affected.

[('Afghanistan', Decimal('20.14'), Decimal('38.972230')),
 ('Argentina', Decimal('385.54'), Decimal('45.376763')),
 ('Armenia', Decimal('12.64'), Decimal('2.805608')),
 ('Australia', Decimal('1326.90'), Decimal('25.655289')),
 ('Azerbaijan', Decimal('42.69'), Decimal('10.093121')),
 ('Bhutan', Decimal('2.33'), Decimal('0.772506')),
 ('Botswana', Decimal('14.93'), Decimal('2.546402')),
 ('Brazil', Decimal('1448.56'), Decimal('213.196304')),
 ('Brunei Darussalam', Decimal('12.01'), Decimal('0.441725')),
 ('Canada', Decimal('1645.42'), Decimal('38.037204')),
 ('Chile', Decimal('252.73'), Decimal('19.300315')),
 ('China', Decimal('14687.67'), Decimal('1411.100000')),
 ('Colombia', Decimal('270.30'), Decimal('50.930662')),
 ('Costa Rica', Decimal('62.16'), Decimal('5.123105')),
 ('Cyprus', Decimal('25.01'), Decimal('1.237537')),
 ('Dominican Republic', Decimal('78.84'), Decimal('10.999664')),
 ('Ecuador', Decimal('99.29'), Decimal('17.588595')),
 ('El Salvador', Decimal('24.56'), Decimal('6.292731')),
 ('Georgia', Decimal('15.84'), Decimal('3.722716')),
 ('Honduras', Decimal('23.83'), Decimal('10.121763')),
 ('India', Decimal('2667.69'), Decimal('1396.387127')),
 ('Jamaica', Decimal('13.81'), Decimal('2.820436')),
 ('Jordan', Decimal('44.18'), Decimal('10.928721')),
 ('Kiribati', Decimal('0.18'), Decimal('0.126463')),
 ('Mauritius', Decimal('11.40'), Decimal('1.265740')),
 ('Mongolia', Decimal('13.31'), Decimal('3.294335')),
 ('New Caledonia', Decimal('9.44'), Decimal('0.271130')),
 ('Panama', Decimal('53.98'), Decimal('4.294396')),
 ('Paraguay', Decimal('35.43'), Decimal('6.618695')),
 ('Peru', Decimal('201.71'), Decimal('33.304756')),
 ('Rwanda', Decimal('10.18'), Decimal('13.146362')),
 ('Saudi Arabia', Decimal('703.37'), Decimal('35.997107')),
 ('South Africa', Decimal('337.62'), Decimal('58.801927')),
 ('Sri Lanka', Decimal('85.35'), Decimal('21.919000')),
 ('Uruguay', Decimal('53.56'), Decimal('3.429086')),
 ('Uzbekistan', Decimal('59.89'), Decimal('34.232050')),
 ('Zambia', Decimal('18.11'), Decimal('18.927715'))]

### Combining the queries

Using the query and the subquery, determine the average GDP and population for countries with unemployment rates above 5%. Group the results by `Country_name`.

In [7]:
%%sql

SELECT 
    Country_name,
    AVG(Est_gdp_in_billions) AS Avg_GDP,
    AVG(Est_population_in_millions) AS Avg_Population
FROM
    (SELECT 
        Country_name,
        Est_gdp_in_billions,
        Est_population_in_millions
    FROM
        Economic_Indicators
    WHERE
        Pct_unemployment > 5
        AND Time_period = 2020) AS FilteredCountries
GROUP BY
    Country_name;

 * mysql+pymysql://root:***@localhost:3306/united_nations
37 rows affected.

[('Afghanistan', Decimal('20.140000'), Decimal('38.9722300000')),
 ('Argentina', Decimal('385.540000'), Decimal('45.3767630000')),
 ('Armenia', Decimal('12.640000'), Decimal('2.8056080000')),
 ('Australia', Decimal('1326.900000'), Decimal('25.6552890000')),
 ('Azerbaijan', Decimal('42.690000'), Decimal('10.0931210000')),
 ('Bhutan', Decimal('2.330000'), Decimal('0.7725060000')),
 ('Botswana', Decimal('14.930000'), Decimal('2.5464020000')),
 ('Brazil', Decimal('1448.560000'), Decimal('213.1963040000')),
 ('Brunei Darussalam', Decimal('12.010000'), Decimal('0.4417250000')),
 ('Canada', Decimal('1645.420000'), Decimal('38.0372040000')),
 ('Chile', Decimal('252.730000'), Decimal('19.3003150000')),
 ('China', Decimal('14687.670000'), Decimal('1411.1000000000')),
 ('Colombia', Decimal('270.300000'), Decimal('50.9306620000')),
 ('Costa Rica', Decimal('62.160000'), Decimal('5.1231050000')),
 ('Cyprus', Decimal('25.010000'), Decimal('1.2375370000')),
 ('Dominican Republic', Decimal('78.840000'), Decimal('10.9996640000')),
 ('Ecuador', Decimal('99.290000'), Decimal('17.5885950000')),
 ('El Salvador', Decimal('24.560000'), Decimal('6.2927310000')),
 ('Georgia', Decimal('15.840000'), Decimal('3.7227160000')),
 ('Honduras', Decimal('23.830000'), Decimal('10.1217630000')),
 ('India', Decimal('2667.690000'), Decimal('1396.3871270000')),
 ('Jamaica', Decimal('13.810000'), Decimal('2.8204360000')),
 ('Jordan', Decimal('44.180000'), Decimal('10.9287210000')),
 ('Kiribati', Decimal('0.180000'), Decimal('0.1264630000')),
 ('Mauritius', Decimal('11.400000'), Decimal('1.2657400000')),
 ('Mongolia', Decimal('13.310000'), Decimal('3.2943350000')),
 ('New Caledonia', Decimal('9.440000'), Decimal('0.2711300000')),
 ('Panama', Decimal('53.980000'), Decimal('4.2943960000')),
 ('Paraguay', Decimal('35.430000'), Decimal('6.6186950000')),
 ('Peru', Decimal('201.710000'), Decimal('33.3047560000')),
 ('Rwanda', Decimal('10.180000'), Decimal('13.1463620000')),
 ('Saudi Arabia', Decimal('703.370000'), Decimal('35.9971070000')),
 ('South Africa', Decimal('337.620000'), Decimal('58.8019270000')),
 ('Sri Lanka', Decimal('85.350000'), Decimal('21.9190000000')),
 ('Uruguay', Decimal('53.560000'), Decimal('3.4290860000')),
 ('Uzbekistan', Decimal('59.890000'), Decimal('34.2320500000')),
 ('Zambia', Decimal('18.110000'), Decimal('18.9277150000'))]

Using the subquery filters the data first into a derived table, which the main query uses to aggregate with.

## Summary

In this lesson, we used a subquery to determine the average GDP and populations of countries where the unemployment rate is above 5%. We made use of the `FROM` clause. In essence, the subquery in the `FROM` clause can be thought of as creating an intermediate or derived table for the main query to operate upon, even if this table exists only for the duration of the query execution.

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/EAI_Blue_Dark.png"  style="width:200px";/>
</div>